// Autogenerated
export enum ServerCapabilities {
    /**No capability information is available. Cannot be used in combination with any other capability.*/
    NA = 'NA',
    /**Provides current data.*/
    DA = 'DA',
    /**Provides historical data.*/
    HD = 'HD',
    /**Provides alarms and conditions that may require operator interaction.*/
    AC = 'AC',
    /**Provides historical alarms and events.*/
    HE = 'HE',
    /**Supports the Global Discovery Server information model.*/
    GDS = 'GDS',
    /**Only supports the Discovery Services. Cannot be used in combination with any other capability.*/
    LDS = 'LDS',
    /**Supports the Device Integration (DI) information model (see DI).*/
    DI = 'DI',
    /**Supports the Analyser Device Integration (ADI) information model (see ADI).*/
    ADI = 'ADI',
    /**Supports the Field Device Integration (FDI) information model (see FDI).*/
    FDI = 'FDI',
    /**Supports the Field Device Integration (FDI) Communication Server information model (see FDI).*/
    FDIC = 'FDIC',
    /**Supports the PLCopen information model (see PLCopen).*/
    PLC = 'PLC',
    /**Supports the ISA95 information model (see ISA-95).*/
    S95 = 'S95',
    /**Supports the reverse connect capabilities defined in Part 6.*/
    RCP = 'RCP',
    /**Supports the Publisher capabilities defined in Part 14.*/
    PUB = 'PUB',
    /**Supports the AutoID information model.*/
    AUTOID = 'AUTOID',
    /**Supports the MDIS information model.*/
    MDIS = 'MDIS',
    /**Supports the information model for Computerized Numerical Control (CNC) systems.*/
    CNC = 'CNC',
    /**Supports the POWERLINK information model.*/
    PLK = 'PLK',
    /**Supports the FDT information model.*/
    FDT = 'FDT',
    /**Supports the Tobacco Machine Communication (TMC) information model.*/
    TMC = 'TMC',
    /**Supports the CSP+ device profile (CSPPlusForMachine) information model.*/
    CSPP = 'CSPP',
    /**Supports the IEC61850 information model.*/
    _61850 = '61850',
    /**Supports the PackML information model.*/
    PACKML = 'PACKML',
    /**Supports the MTConnect information model.*/
    MTC = 'MTC',
    /**Supports the AutomationML information model.*/
    AUTOML = 'AUTOML',
    /**Supports the Sercos information model.*/
    SERCOS = 'SERCOS',
    /**Supports the MIMOSA information model.*/
    MIMOSA = 'MIMOSA',
    /**Supports the WITSML information model.*/
    WITSML = 'WITSML',
    /**Supports the DEXPI information model.*/
    DEXPI = 'DEXPI',
    /**Supports the IOLINK information model.*/
    IOLINK = 'IOLINK',
    /**Supports the VDMA ROBOTICS information model.*/
    VROBOT = 'VROBOT',
    /**Supports the ProfiNET information model.*/
    PNO = 'PNO'
}